<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
		<string>htm</string>
		<string>shtml</string>
		<string>xhtml</string>
		<string>phtml</string>
		<string>php</string>
		<string>inc</string>
		<string>tmpl</string>
		<string>tpl</string>
		<string>ctp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl|article|aside|canvas|figure|footer|header|hgroup|menu|nav|section|summary)\b.*?&gt;
		|&lt;!--(?!.*--\s*&gt;)
		|^&lt;!--\ \#tminclude\ (?&gt;.*?--&gt;)$
		|&lt;\?(?:php)?.*\b(if|for(each)?|while)\b.+:
		|\{\{?(if|foreach|capture|literal|foreach|php|section|strip)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl|article|aside|canvas|figure|footer|header|hgroup|menu|nav|section|summary)&gt;
		|^(?!.*?&lt;!--).*?--\s*&gt;
		|^&lt;!--\ end\ tminclude\ --&gt;$
		|&lt;\?(?:php)?.*\bend(if|for(each)?|while)\b
		|\{\{?/(if|foreach|capture|literal|foreach|php|section|strip)
		|^[^{]*\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>mHTML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.mhtml</string>
	<key>uuid</key>
	<string>9AD4B5D7-BFFE-40D5-A915-6435F41E4EE7</string>
</dict>
</plist>
